version: '3.1'

volumes:
  pg_kitchen:

services:
  kitchen_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=kitchen_db
    volumes:
      - pg_kitchen:/var/lib/postgresql/data

    ports:
      - "5433:5432"